name: flutter_workspaces
description: Test Task for simle draggable workspaces app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_draggable_gridview: ^0.0.8
  get_it: ^7.6.7
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
